"""empty message

Revision ID: 6342bc295f74
Revises: f0aa82dba1f5
Create Date: 2022-07-27 13:36:57.734707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6342bc295f74'
down_revision = 'f0aa82dba1f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.routine_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
