"""empty message

Revision ID: ab188ea568a1
Revises: b1795904b7f9
Create Date: 2022-08-07 13:03:28.554417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab188ea568a1'
down_revision = 'b1795904b7f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routine', sa.Column('initiated_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routine', 'initiated_time')
    # ### end Alembic commands ###
