"""empty message

Revision ID: b1795904b7f9
Revises: ac489152aae9
Create Date: 2022-07-29 13:54:28.355566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1795904b7f9'
down_revision = 'ac489152aae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routine', 'saved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routine', sa.Column('saved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
