"""empty message

Revision ID: df449f08e42d
Revises: ab188ea568a1
Create Date: 2022-08-08 11:59:58.478861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df449f08e42d'
down_revision = 'ab188ea568a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'start_time')
    # ### end Alembic commands ###
