"""empty message

Revision ID: f0aa82dba1f5
Revises: 007d345dfc63
Create Date: 2022-07-27 13:14:35.596632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0aa82dba1f5'
down_revision = '007d345dfc63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routine', sa.Column('complete_time', sa.DateTime(), nullable=True))
    op.add_column('routine', sa.Column('destination', sa.String(), nullable=True))
    op.add_column('routine', sa.Column('saved', sa.Boolean(), nullable=True))
    op.add_column('routine', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('routine', sa.Column('total_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routine', 'total_time')
    op.drop_column('routine', 'start_time')
    op.drop_column('routine', 'saved')
    op.drop_column('routine', 'destination')
    op.drop_column('routine', 'complete_time')
    # ### end Alembic commands ###
